# Generated by Django 4.2.3 on 2023-07-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time_last', models.DateTimeField(verbose_name='Дата и время последней попытки')),
                ('status_attempts', models.CharField(max_length=20, verbose_name='Статус попытки')),
                ('answer_srv_mail', models.IntegerField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Логика',
                'verbose_name_plural': 'Логика',
                'ordering': ['data_time_last'],
            },
        ),
        migrations.CreateModel(
            name='Posting_tuning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField(verbose_name='Дата и время рассылки')),
                ('period', models.CharField(choices=[('1', 'раз в день'), ('2', 'раз в неделю'), ('3', 'раз в месяц')], default='1', max_length=20, verbose_name='Период рассылки')),
                ('status', models.TextField(blank=True, max_length=15, null=True, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
                'ordering': ['data_start'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_letter', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('body_letter', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('clients', models.ManyToManyField(to='clients.client')),
                ('logic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.logic')),
                ('tining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting_tuning')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['topic_letter'],
            },
        ),
    ]
