# Generated by Django 4.2.3 on 2023-07-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time_last', models.DateField(verbose_name='Дата и время последней попытки')),
                ('status_attempts', models.BooleanField(default=True, verbose_name='Статус попытки')),
                ('answer_srv_mail', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Логика',
                'verbose_name_plural': 'Логика',
                'ordering': ['data_time_last'],
            },
        ),
        migrations.CreateModel(
            name='Posting_tuning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField(verbose_name='Дата и время рассылки')),
                ('period', models.CharField(choices=[('раз в день', '1'), ('раз в неделю', '2'), ('раз в месяц', '3')], default='раз в день', max_length=15)),
                ('status', models.TextField(blank=True, null=True, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
                'ordering': ['data_start'],
            },
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['topic_letter'], 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
    ]
