# Generated by Django 4.2.3 on 2023-07-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_logic_posting_tuning_alter_letter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='tining',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posting.posting_tuning'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logic',
            name='data_time_last',
            field=models.DateTimeField(verbose_name='Дата и время последней попытки'),
        ),
    ]
