# Generated by Django 4.2.3 on 2023-07-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_letter_tining_alter_logic_data_time_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='logic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posting.logic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posting_tuning',
            name='period',
            field=models.CharField(choices=[('раз в день', '1'), ('раз в неделю', '2'), ('раз в месяц', '3')], default='раз в день', max_length=15, verbose_name='Период рассылки'),
        ),
    ]
