# Generated by Django 4.2.3 on 2023-07-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_alter_letter_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='status_attempts',
            field=models.IntegerField(default=1, verbose_name='Статус попытки'),
        ),
    ]
