# Generated by Django 4.2.3 on 2023-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_alter_logic_status_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное имя')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарии')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1, null=True, verbose_name='Пол')),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterField(
            model_name='logic',
            name='answer_srv_mail',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='status_attempts',
            field=models.CharField(max_length=20, verbose_name='Статус попытки'),
        ),
        migrations.AlterField(
            model_name='posting_tuning',
            name='period',
            field=models.CharField(choices=[('1', 'раз в день'), ('2', 'раз в неделю'), ('3', 'раз в месяц')], default='1', max_length=20, verbose_name='Период рассылки'),
        ),
        migrations.AddField(
            model_name='letter',
            name='clients',
            field=models.ManyToManyField(to='posting.client'),
        ),
    ]
