# Generated by Django 4.2.3 on 2023-07-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_client_alter_logic_answer_srv_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
    ]
