# Generated by Django 4.2.3 on 2023-07-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное имя')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарии')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1, null=True, verbose_name='Пол')),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['full_name'],
            },
        ),
    ]
