# Generated by Django 4.2.3 on 2023-07-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='Почта'),
            preserve_default=False,
        ),
    ]
